apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  selector:
    app: result
  ports:
  - name: result-service
    port: 80
    targetPort: 80
    nodePort: 32000
  type: NodePort