apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-nodeport
  name: my-nodeport
spec:
  ports:
  - name: 80-80
    nodePort: 30008
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    tier: frontend
  type: NodePort
status:
  loadBalancer: {}
